version: '3'

services:
  server:
    image: edlingaona/exercise
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./migration/main.db:/app/migration/main.db
    environment:
      - NODE_ENV=production
    command: ["/bin/bash", "-c", "./main"]
    network_mode: host
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server
    network_mode: host
